name: Simple workflow to include manual dispatch 

on:
  workflow_dispatch:
  
  
jobs:
  simple_job:
   runs-on: [ubuntu-latest]
  
   steps: 
     - run: echo "hello world!"
      
     - name: "checkout repo"
       uses: actions/checkout@v2

     - name: "Dispatch manual trigger to another repository"
       run: gh workflow run test-github-actions.yaml --ref test-github-actions
       env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
