name: Simple workflow branched out from main 

on:
  workflow_dispatch:
  
  
jobs:
  simple_job:
   runs-on: [ubuntu-latest]
  
   steps: 
     - run: echo "hello world!"
     - run: echo "This workflow is from branch:" ${GITHUB_REF#refs/heads/}
