
name: Test different settings of github actions

# Controls when the workflow will run
# Allows you to run this workflow manually from the Actions tab
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  print-compute-size:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Runs a set of commands using the runners shell
      - name: print RAM
        run: free -mh
      - name: print ROM
        run:  df -h

  clone-private-repo:
     runs-on: self-hosted

     steps:
       # checkout repo containing current workflow
       - uses: actions/checkout@v3
         with:
           submodules: true
       
       - uses: webfactory/ssh-agent@v0.7.0
         with:
            ssh-private-key: ${{ secrets.PERSONAL_SSH_KEY }}
            

